### PR TITLE
Update README to include install and usage instructions

### PR DESCRIPTION
**Pull request by dzier**

### CODE REVIEW

**Comment by adityaiitb** [comment]
Yes. The tool motivation/features and usage should be separate.

**Comment by adityaiitb** [comment]
Apologies, I think I started a review instead of commenting.

**Comment by debermudez** [comment]
@adityaiitb is the best way here to strip the overview section out into its own rst file?

**Comment by adityaiitb** [comment]
For now, yes. We can use that new file to provide a more textual description of the tool and its features e.g. flops, bytes, fprop-bprop correlation, tensor core usage etc.

**Comment by dzier** [comment]
@adityaiitb Keep in mind, the readme is not the User Guide. It's sole purpose is to provide motivation/features/legalize. This is common for all NVIDIA products. I added the quick install and quick start as nod to seeing it being useful, but there are still more ways to install and use PyProf now, including the PyTorch NGC container. All detailed usage and features descriptions belong in the User Guide, which is in the docs/ folder which get compliled and released online here: https://docs.nvidia.com/deeplearning/frameworks/pyprof-user-guide/index.html. Please consider using that as the documentation and updating as needed.

**Pull request merged**
