### PR TITLE
Remove dlprof specific code

### PR DESCRIPTION
**Pull request by debermudez**
Removing dlprof specific code from this repo.

### CODE REVIEW

**Review by dzier — APPROVED** [review]

**Comment by adityaiitb** [comment]
@debermudez Can you do a quick diff with https://github.com/adityaiitb/pyprof2/blob/master/pyprof2/nvtx/nvmarker.py

**Comment by debermudez** [comment]
Yes I can do that.

**Comment by debermudez** [comment]
Differences:

- comments
- some assertions are removed
- additional functions on the ignore list
- additional patching 
In general, this should be good to go.

**Comment by adityaiitb** [comment]
LGTM.

**Review by dzier — APPROVED** [review]

**Pull request merged**
